name: Deploy to OVH via FTP
on:
  push:
    branches:
      - main # ou branch principal do repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@v4

      - name: 📤 Deploy to OVH via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }} # ftp.cluster100.hosting.ovh.net
          username: ${{ secrets.FTP_USERNAME }} # lojacip
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: ./ # ou ./dist ou ./build dependendo do projeto
          server-dir: /home/lojacip/www
          exclude: |
            **/.git/**
            **/node_modules/**
            **/.gitignore
            **/.github/**
            **/README.md
            **/.env
