name: Deploy to OVH via SFTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to OVH via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.cluster100.hosting.ovh.net
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        protocol: sftp
        local-dir: ./
        server-dir: /home/lojacip/www/
        exclude: |
          **/.git*
          **/.git*/**
          **/README.md
          **/.github/**